### PR TITLE
Build fixes

### LINKED ISSUE #558: Parallel buld issues and missing output when building certain objects
The tools build system can only handle one object when building and because we build in parallel multiple the %-in.o rules that in turns starts multiple builds for test.o and cla.o leading to occasional build failures when parallel builds are used. 

Also it looks like there is not output when building certain objects (e.g. tests/cla.o) with both verbose and non-verbose.

### PR DESCRIPTION
**Pull request by tavip**
Backports a patch from upstream to fix build output for test targets and add a workaround to fix parallel builds for tests.  Fixes #558.

Jiri Olsa (1):
  tools/build: Fix -s detection code in tools/build/Makefile.build

Octavian Purdila (2):
  lkl: add tests build barrier
  lkl: don't install tests

 tools/build/Makefile.build | 10 +++++++++-
 tools/lkl/Makefile         | 15 +++++++++++----
 tools/lkl/Targets          | 17 +++++++++++------
 3 files changed, 31 insertions(+), 11 deletions(-)

### CODE REVIEW

**Comment by ddiss** [comment]
> @ddiss could you please check if this fixes the parallel build issue on you side? Not a great solution but it is fairly isolated and simple.

Thanks for the patch! will give it a spin on the Build Service today

**Comment by ddiss** [comment]
The change looks good, but `make install -C tools/lkl` is broken with b4e2599:
```
[  184s]   LD      /home/abuild/rpmbuild/BUILD/lkl-0.6.4+git.2c97ed520d4-build/lkl-0.6.4+git.2c97ed520d4/tools/lkl/.WAIT-in.o
[  184s] gcc -pie -z noexecstack  -o /home/abuild/rpmbuild/BUILD/lkl-0.6.4+git.2c97ed520d4-build/lkl-0.6.4+git.2c97ed520d4/tools/lkl/.WAIT /home/abuild/rpmbuild/BUILD/lkl-0.6.4+git.2c97ed520d4-build/lkl-0.6.4+git.2c97ed520d4/tools/lkl/.WAIT-in.o /home/abuild/rpmbuild/BUILD/lkl-0.6.4+git.2c97ed520d4-build/lkl-0.6.4+git.2c97ed520d4/tools/lkl/liblkl.a -lrt -lpthread 
[  184s] /usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/Scrt1.o: in function `_start':
[  184s] /home/abuild/rpmbuild/BUILD/glibc-2.40/csu/../sysdeps/x86_64/start.S:103:(.text+0x1b): undefined reference to `main'
[  184s] collect2: error: ld returned 1 exit status
[  184s] make: *** [Makefile:106: /home/abuild/rpmbuild/BUILD/lkl-0.6.4+git.2c97ed520d4-build/lkl-0.6.4+git.2c97ed520d4/tools/lkl/.WAIT] Error 1
[  184s] error: Bad exit status from /var/tmp/rpm-tmp.8n6nkp (%install)
```

https://www.gnu.org/software/make/manual/html_node/Parallel-Disable.html doesn't really explain how `.WAIT` should affect `make install`.... perhaps another option would be to add each of the test targets as a `.NOTPARALLEL` prerequisite?

**Review by thehajime — APPROVED** [review]
LGTM.

**Review by ddiss — APPROVED** [review]
Looks good and works for me - thanks!
